name: Keymap-CI

on:
  push:
    branches: [ master, devel ]
  pull_request:
  schedule:
    - cron:  '0 10,18 * * 1'

jobs:
  format-check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Format source code
        run: |
          clang-format-12 -style=file -i keymap.c support.h

      - name: Format check
        run: |
          git status --porcelain --untracked-files=no | xargs -o -I {} test -z \"{}\"

  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env: 
      KEYMAP_NAME: ahueck
      QMK_HOME: ${{github.workspace}}/qmk
      QMK_KEYMAP_HOME: ${{github.workspace}}/qmk/keyboards/redox/keymaps/ahueck
    steps:
      - name: Append PATH environment 
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      
      - name: Install QMK CLI
        run: python3 -m pip install --user qmk

      - name: Setup QMK
        run: qmk setup -y -H ${{env.QMK_HOME}}

      - name: Checkout keymap
        uses: actions/checkout@v2
        with:
          path: ${{env.QMK_KEYMAP_HOME}}

      - name: Build Redox keymap
        run: qmk compile -kb redox/rev1 -km ${{env.KEYMAP_NAME}}
