name: Keymap-CI

on:
  push:
    branches: [ master, devel ]
  pull_request:

jobs:
  build-and-run-test:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Environment vars
        run: |
          echo "KEYMAP_NAME=ahueck" >> $GITHUB_ENV
          echo "KEYMAP_HOME=$GITHUB_WORKSPACE/ahueck" >> $GITHUB_ENV
          echo "QMK_HOME=$GITHUB_WORKSPACE/qmk" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          path: ${KEYMAP_NAME}

      - name: ls ...
        run: |
          ls
          ls ${KEYMAP_HOME}
          ls ${GITHUB_WORKSPACE}
          exit 1

      - name: Install QMK CLI
        run: python3 -m pip install --user qmk

      - name: Setup QMK
        run: qmk setup -y -H ${QMK_HOME}

      - name: Setup keymap location
        run: cp -R ${KEYMAP_HOME}  ${QMK_HOME}/keyboards/redox/keymaps

      - name: Build Redox keymap
        run: qmk compile -kb redox/rev1 -km ahueck