name: Keymap-CI

on:
  push:
    branches: [ master, devel ]
  pull_request:
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  format-check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Add LLVM 21 Repository
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /usr/share/keyrings/llvm-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/llvm-archive-keyring.gpg] http://apt.llvm.org/noble/ llvm-toolchain-noble-21 main" | sudo tee /etc/apt/sources.list.d/llvm.list

      - name: Update and Install
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-21

      - name: Format source code
        run: clang-format-21 -style=file -i keymap.c support.h config.h

      - name: Format check
        run: |
          git status --porcelain --untracked-files=no | xargs -o -I {} test -z \"{}\"

  build:
    runs-on: ubuntu-24.04

    env: 
      KEYMAP_NAME: ahueck
      QMK_HOME: ${{ github.workspace }}/qmk_firmware
      QMK_KEYMAP_HOME: ${{ github.workspace }}/qmk_firmware/keyboards/redox/keymaps/ahueck

    steps:
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14.2'

      - name: Install QMK CLI
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install qmk

      - name: Append PATH environment 
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      
      - name: Install QMK requirements
        run: curl -fsSL https://install.qmk.fm | sh

      - name: Setup QMK
        run: qmk setup -y -H ${{ env.QMK_HOME }}

      - name: QMK modules
        working-directory: ${{ env.QMK_HOME }}
        run: |
          mkdir -p modules
          git submodule add https://github.com/getreuer/qmk-modules.git modules/getreuer
          git submodule update --init --recursive

      - name: Checkout keymap
        uses: actions/checkout@v6
        with:
          path: ${{ env.QMK_KEYMAP_HOME }}

      - name: Build Redox keymap
        run: qmk compile -kb redox/rev1 -km ${{ env.KEYMAP_NAME }}

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v6
        with:
          name: firmware
          path: ${{ env.QMK_HOME }}/redox_rev1_base_${{ env.KEYMAP_NAME }}.hex