name: Keymap-CI

on:
  push:
    branches: [ master, devel ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    env: 
      KEYMAP_NAME: ahueck
      KEYMAP_REPO_HOME: ${{github.workspace}}/ahueck
      QMK_HOME: ${{github.workspace}}/qmk
      QMK_KEYMAP_HOME: ${{github.workspace}}/qmk/keyboards/redox/keymaps/
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ env.KEYMAP_REPO_HOME }}

      - name: Install QMK CLI
        run: python3 -m pip install --user qmk

      - name: Setup QMK
        run: qmk setup -y -H ${QMK_HOME}

      - name: Setup keymap location
        run: cp -R ${{ env.KEYMAP_REPO_HOME }} ${{ env.QMK_KEYMAP_HOME }}

      - name: Build Redox keymap
        run: qmk compile -kb redox/rev1 -km ${{ env.KEYMAP_NAME }}